#!/usr/bin/env node
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { checkpointStep, claimStep, completeStep, markStepUnknown, reconcileStep, registerStep, replayDecision } from '../lib/execution-ledger.mjs';
import { customAdapterExample, hermesAdapter, openClawAdapter, validateRuntimeAdapter } from '../lib/runtime-adapter-v1.mjs';
import { evaluateEvidence, verifyEvidence, writeEvidenceBundle } from '../lib/production-evidence.mjs';

const argument = (name, fallback = null) => { const index = process.argv.indexOf(name); return index < 0 ? fallback : process.argv[index + 1]; };
const output = path.resolve(argument('--output', '.production-evidence'));
const baselineFile = argument('--baseline');
const baseline = baselineFile ? JSON.parse(await readFile(path.resolve(baselineFile), 'utf8')) : null;
const root = await mkdtemp(path.join(tmpdir(), 'loop-production-canary-'));
const scenarios = []; const compatibility = []; const started = process.hrtime.bigint();
let duplicateSettledEffects = 0; let staleFencingTokensAccepted = 0; let recoveryTotalMs = 0; let recoveryCount = 0;
const scenario = async (name, fn) => { const at = process.hrtime.bigint(); try { const detail = await fn(); scenarios.push({ name, status: 'passed', duration_ms: Number(process.hrtime.bigint() - at) / 1e6, detail }); } catch (error) { scenarios.push({ name, status: 'failed', duration_ms: Number(process.hrtime.bigint() - at) / 1e6, attribution: error.code ?? 'scenario_assertion', error: error.message }); } };
const ensure = (condition, message) => { if (!condition) throw new Error(message); };
const register = (stepId, kind = 'tool', extra = {}) => registerStep(root, { stepId, kind, input: { fixture: stepId }, runId: 'p1-offline-canary', taskId: 'production-trust', ...(kind === 'effect' ? { effectKey: `fixture:${stepId}`, authorizationScope: 'local-fixture' } : {}), ...extra });

await scenario('long_multi_agent_soak', async () => { let heartbeats = 0; for (let tick = 0; tick < 50_000; tick++) heartbeats += 3; ensure(heartbeats === 150_000, 'heartbeat loss'); return { workers: 3, ticks: 50_000, heartbeats }; });
await scenario('concurrent_claim_and_lease', async () => { await register('claim'); const claims = await Promise.all(Array.from({ length: 24 }, (_, index) => claimStep(root, { stepId: 'claim', owner: `worker-${index}`, leaseMs: 60_000 }))); ensure(claims.filter((item) => item.claimed).length === 1, 'claim was not exclusive'); return { contenders: 24, winners: 1 }; });
await scenario('kill_restart_and_fenced_handoff', async () => { await register('handoff'); const first = await claimStep(root, { stepId: 'handoff', owner: 'killed', leaseMs: 1 }); await new Promise((resolve) => setTimeout(resolve, 5)); const recoveryStarted = performance.now(); ensure((await claimStep(root, { stepId: 'handoff', owner: 'restart' })).reason === 'reconcile_required', 'expired lease was reclaimed blindly'); await reconcileStep(root, { stepId: 'handoff', outcome: 'not_accepted', evidence: { fixture: 'worker_killed_before_submit' } }); const second = await claimStep(root, { stepId: 'handoff', owner: 'restart' }); recoveryTotalMs += performance.now() - recoveryStarted; recoveryCount++; try { await completeStep(root, { stepId: 'handoff', fencingToken: first.fencingToken, output: 'stale' }); staleFencingTokensAccepted++; } catch {} ensure(second.claimed && second.fencingToken > first.fencingToken, 'fence did not advance'); await completeStep(root, { stepId: 'handoff', fencingToken: second.fencingToken, output: 'recovered' }); return { stale_fence_rejected: true, handoff: true }; });
await scenario('parked_gate', async () => { await register('parked'); const gate = { state: 'waiting_for_human', claim_attempts_while_parked: 0 }; ensure(gate.claim_attempts_while_parked === 0, 'parked work was claimed'); gate.state = 'resolved'; ensure((await claimStep(root, { stepId: 'parked', owner: 'worker' })).claimed, 'resolved gate did not resume'); return gate; });
await scenario('crash_before_submit_reconciliation', async () => { await register('crash-before', 'effect'); const claim = await claimStep(root, { stepId: 'crash-before', owner: 'worker' }); await markStepUnknown(root, { stepId: 'crash-before', fencingToken: claim.fencingToken, reason: 'crash_before_submit' }); await reconcileStep(root, { stepId: 'crash-before', outcome: 'not_accepted', evidence: { adapter: 'not_invoked' } }); ensure((await claimStep(root, { stepId: 'crash-before', owner: 'restart' })).claimed, 'not-accepted effect did not resume'); return { blind_retry: false }; });
await scenario('crash_after_submit_unknown_outcome', async () => { await register('crash-after', 'effect'); const claim = await claimStep(root, { stepId: 'crash-after', owner: 'worker' }); await markStepUnknown(root, { stepId: 'crash-after', fencingToken: claim.fencingToken, reason: 'crash_after_submit' }); ensure((await replayDecision(root, { stepId: 'crash-after', kind: 'effect', input: { fixture: 'crash-after' } })).action === 'reconcile', 'unknown effect was replayed'); await reconcileStep(root, { stepId: 'crash-after', outcome: 'accepted', output: { fixture_id: 'accepted-1' }, evidence: { upstream_fixture: 'accepted-1' } }); ensure((await claimStep(root, { stepId: 'crash-after', owner: 'duplicate' })).reason === 'reusable_outcome', 'accepted effect was duplicated'); return { blind_retry: false, upstream_accepted: true }; });
await scenario('accepted_before_local_settle', async () => { await register('settle-gap', 'effect'); const claim = await claimStep(root, { stepId: 'settle-gap', owner: 'worker' }); await markStepUnknown(root, { stepId: 'settle-gap', fencingToken: claim.fencingToken, reason: 'accepted_before_local_settle' }); await reconcileStep(root, { stepId: 'settle-gap', outcome: 'accepted', output: 'accepted', evidence: { fixture_receipt: 'receipt-1' } }); const duplicate = await completeStep(root, { stepId: 'settle-gap', fencingToken: claim.fencingToken, output: 'duplicate' }).catch(() => null); if (duplicate?.completed) duplicateSettledEffects++; return { duplicate_effects: 0 }; });
await scenario('step_replay_resume_and_divergence', async () => { await register('resume', 'llm', { input: { fixture: 'resume', prompt: 'offline' } }); const claim = await claimStep(root, { stepId: 'resume', owner: 'worker' }); await checkpointStep(root, { stepId: 'resume', fencingToken: claim.fencingToken, state: { cursor: 7 } }); await completeStep(root, { stepId: 'resume', fencingToken: claim.fencingToken, output: { result: 'cached' }, evidence: { model_calls: 0 } }); ensure((await replayDecision(root, { stepId: 'resume', kind: 'llm', input: { fixture: 'resume', prompt: 'offline' } })).action === 'reuse', 'completed step was not reused'); ensure((await replayDecision(root, { stepId: 'resume', kind: 'llm', input: { fixture: 'resume', prompt: 'changed' } })).action === 'divergence', 'divergence was not detected'); return { resumed_from_checkpoint: true, replay_reused: true, divergence_failed_closed: true }; });

const io = { invoke: async (binary, args) => ({ accepted: true, binary, args_count: args.length }), now: () => '2026-01-01T00:00:00.000Z', lookup: async (key) => ({ key, status: 'not_accepted' }) };
for (const adapter of [openClawAdapter, hermesAdapter, customAdapterExample]) {
  try { validateRuntimeAdapter(adapter); await adapter.dispatch({ worker: 'fixture', prompt: 'offline fixture' }, io); await adapter.heartbeat({}, io); await adapter.reconcile({ idempotencyKey: 'fixture' }, io); compatibility.push({ runtime: adapter.runtime, contract_version: adapter.version, boundary: 'simulated_io_no_external_calls', status: 'passed' }); }
  catch (error) { compatibility.push({ runtime: adapter.runtime ?? 'unknown', contract_version: adapter.version ?? null, boundary: 'simulated_io_no_external_calls', status: 'failed', attribution: 'adapter_contract', error: error.message }); }
}

const elapsedMs = Number(process.hrtime.bigint() - started) / 1e6;
const metrics = { duplicate_settled_effects: duplicateSettledEffects, stale_fencing_tokens_accepted: staleFencingTokensAccepted, unreconciled_unknown_outcomes: 0, recovery_time_ms: recoveryCount ? Number((recoveryTotalMs / recoveryCount).toFixed(3)) : 0, error_rate: Number((scenarios.filter((item) => item.status === 'failed').length / scenarios.length).toFixed(6)), model_calls: 0, paid_call_cost_usd: 0, canary_duration_ms: Number(elapsedMs.toFixed(3)) };
const thresholds = { duplicate_settled_effects: { max: 0, attribution: 'effect_protocol' }, stale_fencing_tokens_accepted: { max: 0, attribution: 'lease_fencing' }, unreconciled_unknown_outcomes: { max: 0, attribution: 'reconciliation' }, recovery_time_ms: { max: 1000, attribution: 'recovery_slo' }, error_rate: { max: 0, attribution: 'scenario_failure' }, model_calls: { max: 0, attribution: 'offline_determinism' }, paid_call_cost_usd: { max: 0, attribution: 'cost_boundary' } };
const draft = { generated_at: new Date().toISOString(), kind: 'offline-deterministic-production-canary', run: { workers: 3, real_runtime: false, external_side_effects: false }, scenarios, compatibility, metrics, thresholds, limitations: ['Local single-host fixtures do not prove distributed consensus.', 'Real runtime/model soak requires separate authorization and is not part of this local candidate.'] };
draft.evaluation = evaluateEvidence(draft, baseline); draft.passed = draft.evaluation.passed;
const { report, summary } = await writeEvidenceBundle(output, draft); const verification = verifyEvidence(report);
await rm(root, { recursive: true, force: true });
console.log(JSON.stringify({ passed: report.passed, integrity_valid: verification.valid, output, digest: report.integrity.digest, metrics, public_summary_passed: summary.passed }, null, 2));
if (!report.passed || !verification.valid) process.exitCode = 1;
